"""Build stratified K-fold cross-validation splits over ALL labeled images.

Why: the shipped split gives a 10-image validation set. A single mAP number on
10 images is dominated by sampling noise, so it cannot rank two training
recipes that differ by a few points. Pooling the 61 train + 10 val images and
running K-fold gives a mean +/- std over the whole labeled set instead.

Stratification is on the *class-presence signature* of each image (which of
Empty / Tweezers / Needle_driver appear in it), so every fold sees a similar
class mix - important because Empty is the minority class.

Example:
    python src/make_folds.py --labeled /home/student/hw1/labeled_image_data \
        --k 5 --out datasets/folds --yaml-dir data/folds
"""
import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path

IMG_EXTS = {".png", ".jpg", ".jpeg", ".bmp"}
CLASS_NAMES = {0: "Empty", 1: "Tweezers", 2: "Needle_driver"}
YAML_TMPL = """# Auto-generated by make_folds.py - fold {k} of {K}
path: {root}
train: {train_txt}
val: {val_txt}

names:
  0: Empty
  1: Tweezers
  2: Needle_driver
"""


def label_path_for(img: Path) -> Path:
    """YOLO convention: .../images/... -> .../labels/....txt"""
    parts = list(img.parts)
    for i in range(len(parts) - 1, -1, -1):
        if parts[i] == "images":
            parts[i] = "labels"
            break
    return Path(*parts).with_suffix(".txt")


def read_classes(img: Path) -> Counter:
    lp = label_path_for(img)
    counts = Counter()
    if not lp.exists():
        return counts
    for line in lp.read_text().splitlines():
        line = line.strip()
        if line:
            counts[int(line.split()[0])] += 1
    return counts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--labeled", required=True,
                    help="labeled_image_data root (images/{train,val})")
    ap.add_argument("--k", type=int, default=5)
    ap.add_argument("--out", required=True, help="dir for the fold txt lists")
    ap.add_argument("--yaml-dir", required=True, help="dir for the fold yamls")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    labeled = Path(args.labeled).resolve()
    out = Path(args.out).resolve()
    yaml_dir = Path(args.yaml_dir)
    out.mkdir(parents=True, exist_ok=True)
    yaml_dir.mkdir(parents=True, exist_ok=True)

    imgs = sorted(p for p in (labeled / "images").rglob("*")
                  if p.suffix.lower() in IMG_EXTS)
    if not imgs:
        raise SystemExit(f"no images found under {labeled / 'images'}")

    # Group by class-presence signature, then deal round-robin into folds so
    # each fold gets a proportional slice of every signature group.
    groups = defaultdict(list)
    per_img_counts = {}
    for img in imgs:
        c = read_classes(img)
        per_img_counts[img] = c
        groups[tuple(sorted(c.keys()))].append(img)

    folds = [[] for _ in range(args.k)]
    cursor = 0
    for sig in sorted(groups, key=lambda s: (-len(groups[s]), s)):
        members = groups[sig]
        # deterministic shuffle within the group
        rng_order = sorted(members, key=lambda p: hash((args.seed, p.name)) & 0xFFFFFFFF)
        for img in rng_order:
            folds[cursor % args.k].append(img)
            cursor += 1

    summary = {"k": args.k, "total_images": len(imgs), "folds": []}
    for i in range(args.k):
        val_imgs = sorted(folds[i])
        train_imgs = sorted(p for j in range(args.k) if j != i for p in folds[j])

        train_txt = out / f"fold{i}_train.txt"
        val_txt = out / f"fold{i}_val.txt"
        train_txt.write_text("\n".join(str(p) for p in train_imgs) + "\n")
        val_txt.write_text("\n".join(str(p) for p in val_imgs) + "\n")

        yaml_path = yaml_dir / f"fold{i}.yaml"
        yaml_path.write_text(YAML_TMPL.format(
            k=i, K=args.k, root=out, train_txt=train_txt, val_txt=val_txt))

        box_counts = Counter()
        for p in val_imgs:
            box_counts.update(per_img_counts[p])
        summary["folds"].append({
            "fold": i,
            "n_train": len(train_imgs),
            "n_val": len(val_imgs),
            "val_boxes": {CLASS_NAMES.get(c, c): n
                          for c, n in sorted(box_counts.items())},
            "yaml": str(yaml_path),
        })
        print(f"fold {i}: train {len(train_imgs):3d}  val {len(val_imgs):3d}  "
              f"val boxes {dict(sorted(box_counts.items()))}  -> {yaml_path}")

    (out / "folds_summary.json").write_text(json.dumps(summary, indent=2))
    print(f"\nwrote {args.k} folds to {out} and yamls to {yaml_dir}")


if __name__ == "__main__":
    main()
